### ISSUE TITLE
Error Not Showing

### ISSUE THREAD

**Issue by sabrespectre** [labo89/nusdm#2]
When theres a unpack error, the program just terminate process and shows decryption is successful, without warning.

**Comment by labo89** [comment]
Hey, which title?

**Comment by sabrespectre** [comment]
Assassins Creed 3. This title have a common problem in decrypting, the first batch of files are always corrupt on both locations (USA and EUR) from servers.

**Comment by labo89** [comment]
Seems to be a general problem with the decryption tool: https://www.reddit.com/r/CemuPiracy/comments/dn5wek/failed_to_verify_h0_hash_assassins_creed/

I will change the log entry. CDecrypt still reports return code 0 even if decrypt fails.
