### ISSUE TITLE
Can't download games

### ISSUE THREAD

**Issue by ooxlk** [labo89/nusdm#3]
When I click "Download title" these lines are shown and nothing goes further.
(https://user-images.githubusercontent.com/76644705/146925029-f44b4b71-188e-44ce-b5df-445a497b8c77.png)

**Comment by hexadezi** [comment]
There is no reliable title id. The tool can not download the tmd file. If you have a correct id, you can add it to the titledb.

https://ccs.cdn.c.shop.nintendowifi.net/ccs/download/0005000010195D00/tmd
